### ISSUE TITLE
How to send Authorization Header with mutation?

### ISSUE THREAD

**Issue by JohannesKlauss** [PabloSzx/gqless-hooks#1]
Thank you for this awesome library.
Is it possible to send headers along a executed mutation? I need to send an authorization header to access my endpoint.

**Comment by JohannesKlauss** [comment]
I just checked the code and it seems like there is no option to send additional headers.
So I created a PR #2  to support this feature.

**Comment by PabloSzx** [comment]
Hi, thanks for the PR, I won't close this issue yet tho, because I will improve this functionality later today to specify headers on hooks too. :ok_hand:

**Comment by PabloSzx** [comment]
added headers on hooks, v0.1.8 :tada:
