### ISSUE TITLE
Can't upload files

### ISSUE THREAD

**Issue by yovanoc** [PabloSzx/gqless-hooks#4]
Hello

We can't upload files with this useMutation hook because its trying to JSON.stringify the file I think and the server return a BadRequest, thanks

**Comment by PabloSzx** [comment]
Interesting problem, the thing is, I would have to make an implementation like [apollo-upload-client](https://github.com/jaydenseric/apollo-upload-client/blob/master/src/index.js), and also I would need to make a test environment to check it, which is not trivial at all.

**Comment by PabloSzx** [comment]
Added support for GraphQL Upload in the new gqless! 🎉 

https://gqless.com/core/graphql-upload
